apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: visitor-app
type: Opaque
stringData:
  POSTGRES_DB: visitordb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: MySecurePassword123!